### PR TITLE
fix(sessions): drop unsupported part_metadata before Vertex appendEvent

### LINKED ISSUE #6014: A2A + VertexAiSessionService: part_metadata in event content rejected by Agent Engine Sessions appendEvent (400 INVALID_ARGUMENT) — regression in 2.2.0
### Environment
- `google-adk` 2.2.0
- `google-genai` 2.8.0
- Vertex backend (`GOOGLE_GENAI_USE_VERTEXAI=TRUE`), durable sessions via `VertexAiSessionService` (Agent Engine)
- Agent exposed as an A2A server; the A2A client sends message parts that carry `metadata`

### Symptom
Every turn fails while handling the A2A request:

```
400 INVALID_ARGUMENT. Invalid JSON payload received.
Unknown name "part_metadata" at 'event.content.parts[0]': Cannot find field.
```

### Root cause
- `a2a/converters/part_converter.convert_a2a_part_to_genai_part` copies the inbound A2A part's `metadata` into `genai.types.Part.part_metadata`.
- The resulting event is persisted via `VertexAiSessionService.append_event`, which serializes `part_metadata` (snake_case) into the Sessions request; the Agent Engine Sessions API schema has no such field → 400, and the turn aborts.
- This is consistent with genai's own contract that `part_metadata` is "not supported in Vertex AI" — `_Part_to_vertex` raises on it for `generateContent` — but the session-append path does not strip it.

### Expected
`part_metadata` should not reach Vertex / Agent Engine. Either don't populate it from A2A metadata when running on Vertex, or strip it before `appendEvent` serialization (mirroring `_Part_to_vertex`).

### Regression
Works on `google-adk` 2.1.0; breaks after upgrading to 2.2.0.

### PR DESCRIPTION
**Pull request by rynecheow**
## Description

`google.genai` `Part.part_metadata` is a Gemini Developer API-only field — the model path already guards it in genai's `_Part_to_vertex` (raises for Vertex). But `VertexAiSessionService.append_event` serialised it into both the `content` and `raw_event` payloads, and the Vertex AI Agent Engine Sessions `appendEvent` API rejects it:

```
400 INVALID_ARGUMENT. Invalid JSON payload received.
Unknown name "part_metadata" at 'event.content.parts[0]': Cannot find field.
```

This crashes **every turn** for agents whose events carry `part_metadata`. A common trigger: ADK's own A2A part converter (`a2a/converters/part_converter.convert_a2a_part_to_genai_part`) copies inbound A2A part metadata into `Part.part_metadata`, so any A2A-fronted agent using `VertexAiSessionService` (durable Agent Engine sessions) on Vertex fails on the first turn.

## Fix

Add `_drop_vertex_unsupported_part_fields`, which removes `part_metadata` (tolerant of the `partMetadata` alias) from the serialised content, and apply it to both `config['content']` and `config['raw_event']['content']` before the `appendEvent` call. This mirrors the existing genai `_Part_to_vertex` guard for the model path.

## Testing

- New regression test `test_append_event_strips_unsupported_part_metadata` asserts `part_metadata` is absent from both the `content` and `raw_event` payloads while the part text is preserved. Verified it fails without the fix (the field is present in the dump pre-strip).
- Full `tests/unittests/sessions/test_vertex_ai_session_service.py` suite passes (35 tests).
- `isort` + `pyink` applied per repo config.

Fixes #6014

### CODE REVIEW

**Comment by rohityan** [comment]
Hi @rynecheow , Thank you for your contribution! We appreciate you taking the time to submit this pull request. Your PR has been received by the team and is currently under review. We will provide feedback as soon as we have an update to share.

**Comment by rohityan** [comment]
Hi @GWeale , can you please review this.
