### ISSUE TITLE
ADK Web with MCP Examples

### ISSUE THREAD

**Issue by elliott-marut** [google/adk-python#463]
Can anyone confirm that these are working with ADK 0.3?  

https://google.github.io/adk-docs/tools/mcp-tools/#example-1-file-system-mcp-server

Tried with both a Docker install and a clean local .venv to set up ADK.  

Having the exact code from the example + the default init file.  

`from . import agent
`

It seems like the basic async agent creation is not working with ADK web.  There is even this error if there is no MCP tool use at all (while still maintaining the async method).  

`2025-04-29 22:07:56,492 - ERROR - fast_api.py:637 - Error in event_generator: module 'mcp' has no attribute 'agent'
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/agentdeployment-9TtSrW0h-py3.13/lib/python3.13/site-packages/google/adk/cli/fast_api.py", line 625, in event_generator
    runner = await _get_runner_async(req.app_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/agentdeployment-9TtSrW0h-py3.13/lib/python3.13/site-packages/google/adk/cli/fast_api.py", line 796, in _get_runner_async
    root_agent = await _get_root_agent_async(app_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/agentdeployment-9TtSrW0h-py3.13/lib/python3.13/site-packages/google/adk/cli/fast_api.py", line 774, in _get_root_agent_async
    if getattr(agent_module.agent, "root_agent"):
               ^^^^^^^^^^^^^^^^^^
AttributeError: module 'mcp' has no attribute 'agent'
`

### To Reproduce:

Follow the quickstart in a fresh environment:
https://google.github.io/adk-docs/get-started/quickstart/
Replace agent.py with code from 
https://google.github.io/adk-docs/tools/mcp-tools/#example-1-file-system-mcp-server
(or any other)
run adk web
try to chat anything. 

If anyone could confirm this is working for them, or any steps that may be missing that would be appreciated.

**Comment by kavinkumar807** [comment]
@elliott-marut will try to reproduce and let you know

**Comment by maruti123** [comment]
Example 2 (Google maps mcp) is working with ADK 0.3 for me! 
`async def create_agent():
  """Gets tools from MCP Server."""
  
  tools, exit_stack = await MCPToolset.from_server(
      connection_params=StdioServerParameters(
          command='npx',
          args=["-y",
                "@modelcontextprotocol/server-google-maps",
          ],
          # Pass the API key as an environment variable to the npx process
          env={
              "GOOGLE_MAPS_API_KEY": Maps_API_KEY
          }
      )
  )
  tools_list = tools if isinstance(tools, list) else [tools]
  agent = Agent(
      model='gemini-2.0-flash', # Adjust if needed
      name='PartnerAIAssistant',
      instruction='Help user with mapping, directions and weather using available tools.',
      tools=tools_list + [weather_tool, time_tool]
  )
  return agent, exit_stack


root_agent = create_agent()`

**Comment by elliott-marut** [comment]
Issue diagnosed.  

Astute readers will note that the folder for the agent was "mcp".  If you name your agent folder anything that will run into conflicts with the rest of the Python set up you can expect to see the same module errors.  

`AttributeError: module 'X' has no attribute 'agent' `
